### ISSUE TITLE
Can't install the package

### ISSUE THREAD

**Issue by HilaryCh** [BackTrackBB/backtrackbb#3]
I have issue installing the package....
It shows error (please see the attached file ):
[Error Message.txt](https://github.com/BackTrackBB/backtrackbb/files/2006816/Error.Message.txt)
Failed building wheel for backtrackbb
and
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.14.26428\\bin\\HostX86\\x64\\link.exe' failed with exit status 1120

I have Microsoft Visual Studio 2017 v.15.7.1 installed with the following workloads: 
Universal Windows Platform Development
Python Development
Visual Studio Extension Development.

I am running Windows 10 with Python 3.6
Is it just me or other people also have the same issue?

**Comment by claudiodsf** [comment]
Hi Hilary,

BackTrackBB has never been tested on Windows: I will try building it on a Win10 virtual machine and hopefully came back with a solution.

As an alternative, you can try installing it on a Linux or macOS (virtual) machine.

**Comment by HilaryCh** [comment]
Thank you very much, Claudio! I will try it!

**Comment by claudiodsf** [comment]
Hi Hillary,
I just opened pull request #4 with Windows support.

Please let me know if that works for you.

**Comment by claudiodsf** [comment]
@HilaryCh Did you have time to test again the installation on Windows?

**Comment by claudiodsf** [comment]
This is fixed by #4.
