### ISSUE TITLE
Multiple channel types

### ISSUE THREAD

**Issue by shicks-seismo** [BackTrackBB/backtrackbb#5]
Hi Natalia and Claudio

I'm just looking into using your code for detecting events using ocean bottom seismometers.
My data has HH? and BH? components, so the first thing that has come to my mind is whether it would be possible in the future to add wildcards or a list in the `channel` parameter of the config file.
Also, I'd quite like to use hydrophone components for P-wave detection, so added flexibility in the channel naming would be awesome :)

**Comment by npoiata** [comment]
Hi Stephen,

You can use a mixture of HH? and BH? component by setting for example
`channel = '*HZ'`

Can you specify what is exactly the naming of the hydrophone components?

**Comment by shicks-seismo** [comment]
Hi Natalia,
Great!
The hydrophones are typically EDH, BHH or BDH.

**Comment by npoiata** [comment]
Ok, I see...
`channel` parameter is a list. So, you could use something like:
`channel = 'BHZ', 'EHZ', 'EDH'` 
or what channels you want to include for P-wave analysis and it should be ok.

Let us know if it works.
