### ISSUE TITLE
Can't run the example data

### ISSUE THREAD

**Issue by primawm** [BackTrackBB/backtrackbb#8]
Hello, I have a problem regarding the example data (Chile data). It shows an error like this:

ValueError: 'box-forced' is not a valid value for adjustable; supported values are 'box', 'datalim'

I attached the file that contains the whole log:
[log.txt](https://github.com/BackTrackBB/backtrackbb/files/5231789/log.txt)

Has anyone experienced the same error on example data or is there any step I missed? I am using Windows 10 and python 3.6. Thanks in advance! This is a very interesting code.

**Comment by claudiodsf** [comment]
Hi, sorry for not having replied.

The issue you mentioned should be resolved since some time.
Feel free to reopen this issue if you're still experiencing problems.
